{{- if and .Values.zeebe.enabled .Values.zeebeGateway.ingress.rest.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "zeebe.names.gateway" . }}-rest
  labels:
    {{- include "zeebe.labels.gateway" . | nindent 4 }}
{{- with .Values.zeebeGateway.ingress.rest.annotations }}
  annotations:
  {{- tpl (toYaml .) $ | nindent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.zeebeGateway.ingress.rest.className }}
  rules:
    {{- if .Values.zeebeGateway.ingress.rest.host }}
    - host: {{ tpl .Values.zeebeGateway.ingress.rest.host $ }}
      http:
    {{- else }}
    - http:
    {{- end }}
        paths:
          - path: {{ .Values.zeebeGateway.ingress.rest.path }}
            pathType: {{ .Values.zeebeGateway.ingress.rest.pathType }}
            backend:
              service:
                name: {{ include "zeebe.names.gateway" . }}
                port:
                  number: {{ .Values.zeebeGateway.service.restPort }}
  {{- if .Values.zeebeGateway.ingress.rest.tls.enabled }}
  tls:
    - hosts:
        - {{ tpl .Values.zeebeGateway.ingress.rest.host $ }}
      {{- if .Values.zeebeGateway.ingress.rest.tls.secretName }}
      secretName: {{ .Values.zeebeGateway.ingress.rest.tls.secretName }}
      {{- end }}
  {{- end }}
{{- end }}
