apiVersion: v2
description: Identity Helm Chart for Kubernetes
name: identity
version: 8.2.33
type: application
icon: https://helm.camunda.io/imgs/camunda.svg
dependencies:
  - name: keycloak
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 12.3.0
    condition: keycloak.enabled
