#
# Camunda - Alpha
#

global:
  # https://github.com/camunda/camunda-platform/releases
  # https://hub.docker.com/u/camunda
  image:
    tag:

console:
  # Camunda Enterprise repository.
  # https://hub.docker.com/r/camunda/console/tags
  image:
    tag: 8.6.0-alpha5

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: 8.6.0-alpha5

operate:
  # https://hub.docker.com/r/camunda/operate/tags
  image:
    tag: 8.6.0-alpha5

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 8.6.0-alpha5

tasklist:
  # https://hub.docker.com/r/camunda/tasklist/tags
  image:
    repository: camunda/tasklist
    tag: 8.6.0-alpha5

webModeler:
  # https://hub.docker.com/r/camunda/web-modeler-restapi
  image:
    # renovate: datasource=docker depName=camunda/web-modeler-restapi
    tag: 8.6.0-alpha5

zeebe:
  # https://hub.docker.com/r/camunda/zeebe/tags
  image:
    repository: camunda/zeebe
    tag: 8.6.0-alpha5

zeebeGateway:
  # https://hub.docker.com/r/camunda/zeebe/tags
  image:
    repository: camunda/zeebe
    tag: 8.6.0-alpha5

#
# Identity
#

identity:
  # https://hub.docker.com/r/camunda/identity/tags
  image:
    repository: camunda/identity
    tag: 8.6.0-alpha5

identityKeycloak:
  # https://hub.docker.com/r/bitnami/keycloak/tags
  image:
    repository: bitnami/keycloak
    tag: 23.0.7
  postgresql:
    # https://hub.docker.com/r/bitnami/postgresql/tags
    image:
      repository: bitnami/postgresql
      tag: 15.8.0

#
# Elasticsearch
#

elasticsearch:
  # https://hub.docker.com/r/bitnami/elasticsearch/tags
  image:
    repository: bitnami/elasticsearch
    tag: 8.15.2
