{{- if and .Values.global.opensearch.enabled .Values.global.opensearch.auth.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "camundaPlatform.fullname" . }}-opensearch
  annotations: {{- toYaml .Values.global.annotations | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.global.opensearch.auth.password | b64enc }}
{{- end }}
