{{- if and .Values.global.elasticsearch.external .Values.global.elasticsearch.auth.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "camundaPlatform.fullname" . }}-elasticsearch
  annotations: {{- toYaml .Values.global.annotations | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.global.elasticsearch.auth.password | b64enc }}
{{- end }}
